services:
  pg-master:
    image: postgres:17
    container_name: pg-master
    environment:
      POSTGRES_DB: people_hub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: replicator
    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
    ports:
      - "5432:5432"
    volumes:
      - pg-master-data:/var/lib/postgresql/data
      - ./docker/master-init.sh:/docker-entrypoint-initdb.d/master-init.sh:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d people_hub" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - pg-cluster

  pg-replica-1:
    image: postgres:17
    container_name: pg-replica-1
    user: postgres
    environment:
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: replicator
      REPLICATION_SLOT: replica_1_slot
    entrypoint: [ "bash", "/usr/local/bin/replica-init.sh" ]
    ports:
      - "5433:5432"
    volumes:
      - pg-replica-1-data:/var/lib/postgresql/data
      - ./docker/replica-init.sh:/usr/local/bin/replica-init.sh:ro
    depends_on:
      pg-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - pg-cluster

  pg-replica-2:
    image: postgres:17
    container_name: pg-replica-2
    user: postgres
    environment:
      REPLICATION_USER: replicator
      REPLICATION_PASSWORD: replicator
      REPLICATION_SLOT: replica_2_slot
    entrypoint: [ "bash", "/usr/local/bin/replica-init.sh" ]
    ports:
      - "5434:5432"
    volumes:
      - pg-replica-2-data:/var/lib/postgresql/data
      - ./docker/replica-init.sh:/usr/local/bin/replica-init.sh:ro
    depends_on:
      pg-master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      - pg-cluster

volumes:
  pg-master-data:
  pg-replica-1-data:
  pg-replica-2-data:

networks:
  pg-cluster:
